import Head from 'next/head';
import Footer from '../components/Footer';
import Header from '../components/Header';
import Sectionone from '../components/Sectionone';
import SectionThree from '../components/SectionThree';
import SectionTwo from '../components/SectionTwo';
import Shortner from '../components/shortner';

export default function Home() {
  return (
    <div className="overflow-hidden">
      <Head>
        <title>url-shortening</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>
        <Header />
      </header>
      <main className=" bg-neutral-100">
        <Shortner />
        <Sectionone />
        <SectionTwo />
        <SectionThree />
      </main>

      <footer className="bg-Neutral-VeryDarkViolet">
        <Footer />
      </footer>
    </div>
  );
}
