import Head from 'next/head';
import Header from '../components/Header';
import Sectionone from '../components/Sectionone';
import Shortner from '../components/shortner';

export default function Home() {
  return (
    <div>
      <Head>
        <title>url-shortening</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>
        <Header />
      </header>
      <main className="px-6">
        <Shortner />
        <Sectionone />
      </main>

      <footer></footer>
    </div>
  );
}
